{% set name = "mod_wsgi" %}
{% set version = '4.6.5' %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

build:
  number: 0
  script: python setup.py install
  entry_points:
    - mod_wsgi-express = mod_wsgi.server:main

source:
  git_rev: {{ version }}
  git_url: https://github.com/GrahamDumpleton/mod_wsgi.git

requirements:
  build:
    - git
    - python {{ python }}
    - httpd
  run:
    - python {{ python }}
    - httpd

about:
  home: https://pypi.python.org/pypi/mod_wsgi
  license: Apache
