{% set httpd_version = '2.4.38' %}

package:
  name: httpd
  version: "{{ httpd_version }}"

build:
  number: 0

source:
  fn: "httpd-{{ httpd_version }}.tar.gz"
  url: "http://mirrors.advancedhosters.com/apache/httpd/httpd-{{ httpd_version }}.tar.gz"
  sha256: 7dc65857a994c98370dc4334b260101a7a04be60e6e74a5c57a6dee1bc8f394a

requirements:
  build:
    - openssl
    - pcre
    - zlib
  run:
    - openssl
    - pcre
    - zlib

about:
  home: http://httpd.apache.org/
  license: Apache
  summary: The Apache HTTP Server Project is an effort to develop and maintain an open-source HTTP server for modern operating systems including UNIX and Windows.
