{% set name = "pytest-dependency" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: {{ version }}
  git_url: https://github.com/RKrahl/pytest-dependency.git

build:
  number: 0
  script: "{{ PYTHON }} setup.py install"

requirements:
  host:
    - pip
    - pytest >=3.6.0
    - python
    - setuptools
  run:
    - pytest >=3.6.0
    - python
    - setuptools

about:
  home: https://github.com/RKrahl/pytest-dependency
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Manage dependencies of tests
  doc_url: https://pytest-dependency.readthedocs.io/
  dev_url: 
